There is a new object LastAddr.java for which the Main java file need…
joov/bcanalysis pull request #9
Opened 2017-04-15 18:26 UTC by PabloDeo

…s to be accomodated. (See the new Main3.java for reference)

(I am not sure how I should modify the Main2.java .)

2017-04-18 08:13 UTC, joov requested changes
Dear Yanghua,
as for the block hashes (starting / ending)  and configurability I still have questions.
As you can see in Main2.java I pushed the curr and last hashes are read from a property file. From the code it is not obvious, if the values from Main2.java or from Main3.java are used. Could you please:
- delete the  fields not used
- use the the way the values are read from BCProperties as specified in Main2.java 

Again I would like to emphesize, that the code should be runnable *without* code changes (changes in .java-files) when restarting or running in another environment than your PC.

2017-04-18 10:09 UTC, PabloDeo commented
Dear Johannes,

I have just pushed the newer version.

Best regards,
Yanghua

2017-04-20 12:46 UTC, joov approved these changes

2017-04-20 12:48 UTC, joov approved these changes
Changes approved

2017-04-20 12:55 UTC, merged